config/routes.rb
Rails.application.routes.draw do
  resources :tutorials
  resources :landing, only: [:index, :show]
  devise_for :users



  root 'landing#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tutorial.rb
class Tutorial < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :tutorials
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index

    @tutorials = Tutorial.paginate(page: params[:page], per_page: 9)
  end

  def show
    @tutorial = Tutorial.find(params[:id])
  end
end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
  before_action :set_tutorial, only: [:show, :edit, :update, :destroy]

  # GET /tutorials
  # GET /tutorials.json
  def index
    @tutorials = Tutorial.all
  end

  # GET /tutorials/1
  # GET /tutorials/1.json
  def show


    if @tutorial.image_link.nil?
      name = "#{current_user.email}" + "#{rand(0..1000)}.png"

      screenshot = Gastly.capture("#{@tutorial.link}", "./app/assets/images/#{name}")

      @tutorial.update_attribute(:image_link, name)
    end
  end

  # GET /tutorials/new
  def new
    @tutorial = Tutorial.new
  end

  # GET /tutorials/1/edit
  def edit
  end

  # POST /tutorials
  # POST /tutorials.json
  def create
    @tutorial = Tutorial.new(tutorial_params)

    respond_to do |format|
      if @tutorial.save
        format.html { redirect_to @tutorial, notice: 'Tutorial was successfully created.' }
        format.json { render :show, status: :created, location: @tutorial }
      else
        format.html { render :new }
        format.json { render json: @tutorial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tutorials/1
  # PATCH/PUT /tutorials/1.json
  def update
    respond_to do |format|
      if @tutorial.update(tutorial_params)
        format.html { redirect_to @tutorial, notice: 'Tutorial was successfully updated.' }
        format.json { render :show, status: :ok, location: @tutorial }
      else
        format.html { render :edit }
        format.json { render json: @tutorial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tutorials/1
  # DELETE /tutorials/1.json
  def destroy
    @tutorial.destroy
    respond_to do |format|
      format.html { redirect_to tutorials_url, notice: 'Tutorial was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tutorial
      @tutorial = Tutorial.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tutorial_params
      params.require(:tutorial).permit(:title, :description, :user_id, :link, :image_link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
end

app/views/landing/index.html.erb
<html lang="en">
 
  <body>
   

<main role="main">

  <section class="jumbotron text-center">
    <div class="container">
      <h1>ShareATutorial</h1>
      <p class="lead text-muted">The fastest way to find the best tutorials</p>
      <p>
        <a href="#" class="btn btn-primary my-2">Join</a>
        <a href="#" class="btn btn-secondary my-2">Explore</a>
      </p>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row">

      <% @tutorials.each do |tutorial| %>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm" style="min-height: 300px;">
        <div class="d-flex flex-row justify-content-center w-100">

          <%= image_tag tutorial.image_link,  style: "height: 100px; width: 50%;"%>

        </div>  


            <div class="card-body">
              <p class="card-text"><%= tutorial.title %></p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                <%= link_to "View", landing_path(tutorial.id), class: 'btn btn-sm btn-outline-secondary' %>
                 
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>

        <% end %>


      
       
      </div>

      <div class="d-flex flex-row justify-content-center p-3">
        <%= will_paginate @tutorials, class: 'p-3' %>


      </div>


    </div>
  </div>

</main>

</body>
</html>

app/views/landing/show.html.erb
<div class="container">

    <div class="d-flex flex-row justify-content-center">

        <div class="col-md-8">
            <div class="card">

                <div class="card-header">

                    <%= @tutorial.title %>
                </div>

                <div class="card-body">

                    <p class="lead">

                        <%= @tutorial.description %>
                    </p>

                    <%= image_tag @tutorial.image_link, style: "width: 100%;" %>



                    <%= link_to @tutorial.link, @tutorial.link %>
                    <br><br>
                    <p>

                        <%= link_to "Back", root_path, class: 'btn btn-outline-secondary' %>

                    </p>

                </div>

            </div>

        </div>

    </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>Album example · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.4/examples/album/">

    <!-- Bootstrap core CSS -->
<link href="/docs/4.4/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/4.4/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/4.4/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/4.4/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
<link rel="icon" href="/docs/4.4/assets/img/favicons/favicon.ico">
<meta name="msapplication-config" content="/docs/4.4/assets/img/favicons/browserconfig.xml">
<meta name="theme-color" content="#563d7c">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="album.css" rel="stylesheet">
    <title>ShareTut</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">ShareATutorial</h4>
          <p class="text-muted">The way to learn quickly web stuff.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Account</h4>
          <ul class="list-unstyled">
            <% if user_signed_in? %>
            <li><%= link_to "Manage Tutorials", tutorials_path, class: 'text-white' %></li>
            <li><%= link_to "Share Tutorial", new_tutorial_path, class: 'text-white' %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'text-white' %></li>
            <% else %>
            <li><%= link_to "Sign In", new_user_session_path, class: 'text-white' %></li>
            <li><%= link_to "Sign Up", new_user_registration_path, class: 'text-white' %></li>


            <% end %>

           
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">

      
      <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2" viewBox="0 0 24 24" focusable="false"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>ShareATutorial</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>
   <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>


    <footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <p>ShareATutorial is &copy; the way to find tutorials!</p>
    <p>New to Bootstrap? <a href="https://getbootstrap.com/">Visit the homepage</a> or read our <a href="/docs/4.4/getting-started/introduction/">getting started guide</a>.</p>
  </div>
</footer>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="/docs/4.4/assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="/docs/4.4/dist/js/bootstrap.bundle.min.js" integrity="sha384-6khuMg9gaYr5AxOqhkVIODVIvm9ynTT5J4V1cfthmT+emCG6yVmEZsRHdxlotUnm" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tutorials/_form.html.erb
  <%= form_with(model: tutorial, local: true) do |form| %>
  <% if tutorial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tutorial.errors.count, "error") %> prohibited this tutorial from being saved:</h2>

      <ul>
      <% tutorial.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control'  %>
  </div>

  <div class="form-group">
    <%= form.hidden_field :user_id, :value => current_user.id %>
  </div>

  <div class="form-group">
    <%= form.label :link %>
    <%= form.text_field :link, class: 'form-control'  %>
  </div>

  <div class="actions">
    <%= form.submit "Add Tutorial", class: 'btn btn-sm btn-outline-success' %>
  </div>
<% end %>

app/views/tutorials/edit.html.erb
<h1>Editing Tutorial</h1>

<%= render 'form', tutorial: @tutorial %>

<%= link_to 'Show', @tutorial %> |
<%= link_to 'Back', tutorials_path %>

app/views/tutorials/index.html.erb
<div class="container">



<p id="notice"><%= notice %></p>

<h1>Tutorials</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>User</th>
      <th>Link</th>
      <th>Image link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tutorials.each do |tutorial| %>
      <tr>
        <td><%= tutorial.title %></td>
        <td><%= tutorial.description %></td>
        <td><%= tutorial.user %></td>
        <td><%= tutorial.link %></td>
        <td><%= tutorial.image_link %></td>
        <td><%= link_to 'Show', tutorial %></td>
        <td><%= link_to 'Edit', edit_tutorial_path(tutorial) %></td>
        <td><%= link_to 'Destroy', tutorial, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
<%= link_to 'New Tutorial', new_tutorial_path %>
<% end %></div>

app/views/tutorials/new.html.erb
<div class="container">

<h1>New Tutorial</h1>

<%= render 'form', tutorial: @tutorial %>

<%= link_to 'Back', tutorials_path %>
</div>

app/views/tutorials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @tutorial.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tutorial.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @tutorial.user %>
</p>

<p>
  <strong>Link:</strong>
  <%= @tutorial.link %>
</p>

<p>
  <strong>Image link:</strong>
  <%= @tutorial.image_link %>
</p>

<%= link_to 'Edit', edit_tutorial_path(@tutorial) %> |
<%= link_to 'Back', tutorials_path %>